management.security.enabled: false
security.basic.enabled: false

server:
    port: 8220

demo:
    domainname: reasonthearchitect.com

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    cloud:
        stream:
            kafka:
                binder:
                    zkNodes: 172.31.55.162
                    brokers: 172.31.55.162
    
metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: filterCarList

